version: "3.8"

services:
    backend:
    image_name: chat-app-backend
    build:
      context: ./backend
    command: npm run dev
    ports:
            - "5000:5000"

    frontend:
      build:
        context: ./frontend
      command: npm run dev
      ports:
      - "5173:5173"
